# Production (override via env vars when deployed)
spring.datasource.url=${PROD_DB_URL:jdbc:postgresql://localhost:5432/library_prod}
spring.datasource.username=${PROD_DB_USER:postgres}
spring.datasource.password=${PROD_DB_PASS:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
