# Local development (Docker Postgres via OrbStack)
spring.datasource.url=jdbc:postgresql://db.oop26.orb.local:5432/library
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
